name: Deploy to AWS ECR & Auto Scaling

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU for ARM64 build
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push ARM64 Docker Image
        env:
          ECR_REGISTRY: 361103953202.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: sensible-debate
          IMAGE_TAG: latest
        run: |
          docker buildx build --platform linux/arm64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --push .

      - name: Trigger EC2 Auto Scaling Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name sensible-debate-asg \
            --region ap-south-1
